---
- name: Lab Nodes
  tower_credential:
    name: Lab Nodes
    state: present
    kind: ssh
    organization: Default
    username: "{{ ansible_user }}"
    password: "{{ hostvars['tower']['ansible_password'] }}"
